### PR TITLE
adds A bunch of files that i dont want to list so heres all the files

### PR DESCRIPTION
**Pull request by Dashtiss**
Repo/
└── Lists/
    ├── AmmoType.md
    ├── Colors.md
    ├── Door-Perms.md
    ├── Doors.md
    ├── Effects.md
    ├── ElevatorType.md
    ├── FirearmType.md
    ├── Items.md
    ├── KeycardPermissions.md
    ├── PlayerPermissions (RemoteAdmin).md
    ├── Prefabs.md
    ├── projectileType.md
    ├── RoleType.md
    ├── SCP914Types.md
    └── SpawnableRooms.md

You can do what every you want to change

### CODE REVIEW

**Comment by Dashtiss** [comment]
can you not change the SpawnableRoom.md

**Comment by Dashtiss** [comment]
it a bit broken

**Comment by Itsyourdriver** [comment]
Woah, sorry for the late response, about to work on merging this within the next few days, thank you as always!

**Comment by Dashtiss** [comment]
It’s ok just let me know when you can merge this

**Comment by Itsyourdriver** [comment]
sorry for the extreme delay, remembered today and figured out how to resolve conflicts (hopefully everything went through properly, though it looks like it did.)

**Pull request merged**
